[project]
name = "my-word2vec"
version = "0.1.0"
description = "Skip-gram word2vec with negative sampling"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "ruff>=0.15.2",
]
